const capabilities = [
  ["01", "Product-minded engineering", "I turn ambiguous business needs into useful, shippable systems."],
  ["02", "Full-stack range", "From React interfaces to APIs, data, cloud infrastructure, and release pipelines."],
  ["03", "AI with a job to do", "RAG, workflow automation, and agentic ideas grounded in measurable outcomes."],
];
const stack = ["TypeScript", "React / Next.js", "Node.js / NestJS", "Python", "AWS", "Docker", "PostgreSQL", "MongoDB", "Redis", "RAG", "n8n", "CI/CD"];

export default function Home() {
  return <main>
    <nav className="nav shell"><a className="wordmark" href="#top"><span>BT</span> Bruno Tomé</a><div className="nav-links"><a href="#work">Selected work</a><a href="#ai-case-study">AI case study</a><a href="#about">About</a><a href="#contact" className="nav-cta">Let&apos;s talk <span>↗</span></a></div></nav>
    <section className="hero shell" id="top"><div className="hero-copy"><p className="eyebrow"><span className="status-dot" /> Available for the next meaningful build</p><h1>Engineering<br /><em>with intent.</em></h1><p className="hero-intro">I&apos;m Bruno, a computer engineer and technology leader who builds products where strong systems meet real human needs.</p><div className="hero-actions"><a className="button button-dark" href="#work">See selected work <span>↓</span></a><a className="text-link" href="mailto:bruno.tome678@gmail.com">bruno.tome678@gmail.com <span>↗</span></a></div></div><div className="hero-art" aria-hidden="true"><div className="orb orb-main"><span>build<br />better</span></div><div className="orb orb-small"><span>03</span></div><div className="orbit orbit-one" /><div className="orbit orbit-two" /><p className="art-note">São Carlos<br />Brazil · 2026</p><p className="art-label">systems / product / people</p></div></section>
    <section className="proof-strip"><div className="shell proof-grid"><div><strong>7+</strong><span>university<br />marketplaces</span></div><div><strong>R$2.5m</strong><span>raised for<br />BeUni</span></div><div><strong>45k</strong><span>records<br />enriched</span></div><div><strong>01</strong><span>founder mindset<br />always on</span></div></div></section>
    <section className="section shell" id="work"><div className="section-heading"><p className="eyebrow">01 / Selected work</p><h2>Making the complex<br /><em>feel simple.</em></h2></div><article className="feature-card"><div className="feature-meta"><span>01 — BeUni / SwagTech</span><span>2019 — 2024</span></div><div className="feature-content"><div><a className="brand-stamp" href="https://beuni.com.br" target="_blank" rel="noreferrer"><span>be</span>uni <small>official site ↗</small></a><h3>From campus<br />commerce to<br /><em>corporate gifting.</em></h3><p>As co-founder and technology leader, I helped take BeUni from a university marketplace MVP to a funded platform. Today, BeUni removes the complexity of buying, storing, managing, and shipping personalized corporate gifts.</p><a className="arrow-link" href="mailto:bruno.tome678@gmail.com?subject=BeUni%20case%20study">Ask me about the build <span>↗</span></a></div><div className="feature-diagram" aria-label="BeUni platform illustration"><div className="diagram-core">BE<br /><small>UNI</small></div><div className="diagram-node node-a">personalize</div><div className="diagram-node node-b">store</div><div className="diagram-node node-c">ship</div></div></div><div className="feature-tags"><span>Product strategy</span><span>Full-stack platform</span><span>SwagTech</span><span>Team leadership</span></div></article><div className="mini-projects"><article><span className="project-index">02</span><div><p className="project-type">Data enrichment · Endeavor</p><h3>45,000 records.<br /><em>One useful database.</em></h3><p>Used JavaScript, APIs, and Google Sheets to turn scattered entrepreneur data into 16,000 actionable entries.</p></div><span className="project-arrow">↗</span></article><article><span className="project-index">03</span><div><p className="project-type">Prototypes · AI systems</p><h3>Less hype.<br /><em>More leverage.</em></h3><p>Exploring RAG, automation, and agentic workflows that earn their place in the product.</p></div><span className="project-arrow">↗</span></article></div></section>
    <section className="ai-case-study" id="ai-case-study"><div className="shell ai-case-grid"><div><p className="eyebrow eyebrow-light">02 / AI case study</p><h2>A portfolio<br /><em>built in conversation.</em></h2></div><div className="ai-case-copy"><p className="large-copy">I built this portfolio fully with AI in chat, using conversation as the interface for product thinking, writing, design direction, coding, iteration, and publishing.</p><p>The case study is the workflow itself: translating a personal story into a clear product, refining the visual system, adding real project context, fixing interaction details, and shipping a working site. AI accelerated the loop; my judgment set the direction and the quality bar.</p><div className="ai-case-tags"><span>Prompt-led product work</span><span>AI-assisted coding</span><span>Human-directed iteration</span></div></div></div></section>
    <section className="dark-section" id="about"><div className="shell about-grid"><div><p className="eyebrow eyebrow-light">02 / The throughline</p><h2>Curiosity is<br /><em>a technical skill.</em></h2></div><div className="about-body"><p className="large-copy">I like being close to the whole picture: the customer problem, the product decision, the architecture, and the person shipping it.</p><p>My background spans engineering, product, sales, logistics, and finance. That range is useful when a team needs someone who can zoom out without losing the details, or zoom in without losing the why.</p><a className="button button-light" href="/cv-bruno-tome.pdf">View my CV <span>↗</span></a></div></div></section>
    <section className="section shell capabilities"><div className="section-heading split-heading"><div><p className="eyebrow">03 / How I work</p><h2>Good work has<br /><em>good questions.</em></h2></div><p className="heading-aside">The best solutions usually appear when engineering is invited into the conversation early.</p></div><div className="cap-grid">{capabilities.map(([number, title, body]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className="stack-section"><div className="shell stack-grid"><div><p className="eyebrow eyebrow-light">04 / Current toolkit</p><h2>Tools are<br /><em>the vocabulary.</em></h2></div><div className="stack-list">{stack.map((item) => <span key={item}>{item}</span>)}</div></div></section>
    <footer className="footer shell" id="contact"><div><p className="eyebrow">05 / Start a conversation</p><h2>Have a hard<br /><em>problem?</em></h2></div><div className="footer-contact"><p>Tell me what you&apos;re building, what&apos;s stuck, or what you&apos;re imagining.</p><a className="footer-email" href="mailto:bruno.tome678@gmail.com">bruno.tome678@gmail.com <span>↗</span></a><div className="socials"><a href="https://github.com/Bruno-Tome">GitHub ↗</a><a href="https://www.linkedin.com/in/brunot-rosa">LinkedIn ↗</a></div></div><div className="footer-bottom"><span>© 2026 Bruno Tomé Rosa</span><span>Made with care in Brazil</span><a href="#top">Back to top ↑</a></div></footer>
  </main>;
}
